steps :
  - name : 'gcr.io/kaniko-project/executor:v1.6.0'
    args :
      - '--destination=asia.gcr.io/$PROJECT_ID/endpoint:latest'
      - '--destination=asia.gcr.io/$PROJECT_ID/endpoint:$SHORT_SHA'
      - '--cache=true'
  - name : 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint : gcloud
    args :
      - 'run'
      - 'deploy'
      - 'endpoint'
      - '--image'
      - 'asia.gcr.io/$PROJECT_ID/endpoint:$SHORT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
