# Generated by Django 4.1.2 on 2022-10-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
