# Generated by Django 4.1.2 on 2022-10-23 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_score', '0002_record_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='update',
        ),
    ]
